
export const FETCH_ALL_POKEMONS= 'FETCH_ALL_POKEMONS';
export const FETCH_SINGLE_POKEMON_SUCCESS='FETCH_SINGLE_POKEMON_SUCCESS';
export const FETCH_ALL_POKEMONS_SUCCESS = 'FETCH_ALL_POKEMONS_SUCCESS'
export const FETCH_ALL_POKEMONS_ERROR = 'FETCH_ALL_POKEMONS_ERROR'
export const LOADING_POKEMON = 'LOADING_POKEMON'